### PR TITLE
Add project: Gaphor

### PR DESCRIPTION
**Pull request by danyeaw**
Thanks for the great resource :heart: 

## Basic info

**Application name**: Gaphor
**Application repo link**: https://github.com/gaphor/gaphor
**Application home link**: https://gaphor.readthedocs.io/
**Application description**: UML Modeling Tool

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [X] Free software with an online source repository.
- [X] Using Python for a considerable part of their functionality.
- [X] Well-known, or at least prominently used in an identifiable niche.
- [X] Maintained or otherwise demonstrably still functional on relevant platforms.
- [X] An application, not a library or framework.

## Additional notability info
Most UML tools are huge enterprise applications like IBM Rhapsody and MagicDraw. This is a simple and quick tool, so it has its own niche. It is the only UML modeling tool written in Python.

### CODE REVIEW

**Comment by danyeaw** [comment]
@mahmoud version 1.0.0 of Gaphor was released yesterday and is packaged for Windows, macOS, and Linux. I think now would be a great time to add it to the list 👍

**Comment by mahmoud** [comment]
Agreed! The new packaging looks great. I'll need to refactor this PR a bit, but will post back here when gaphor is in.

**Comment by mahmoud** [comment]
Put it under docs and graphics, keep up the good work!

**Comment by danyeaw** [comment]
@mahmoud Thanks ♥️

**Pull request closed without merging**
