### PR TITLE
Removes redundant names from descriptions and fills in graphics apps

### PR DESCRIPTION
**Pull request by CameronCairns**

### CODE REVIEW

**Comment by CameronCairns** [comment]
Lmk if I did this correctly. is it more polite to refork whenever I have new commits?

**Comment by mahmoud** [comment]
No refork necessary. 

Looks good! Also, when I rewrote some descriptions, I realized that "free", "open-source", and "Python" are also kinda redundant within the context of the list, so I tend to drop those details as well.

Btw I added a requirements.txt, in case you want to run generate_docs.py. I can do it, too, but you know, in case you felt like previewing on your fork :)

**Comment by CameronCairns** [comment]
Agreed at their redundancy, I didn't notice you did that until I saw merge conflicts for this second PR haha.  I'll keep that in mind for future commits, a little harder to find and replace for that with regex unfortunately.

**Comment by mahmoud** [comment]
No worries, better to have some desc than none, we'll get em next PR :)

**Pull request merged**
