### PR TITLE
Update project: cape to capev2 and fix the sandbox domain

### PR DESCRIPTION
**Pull request by doomedraven**
capev1 is dead and devs doesn't have access to cape.contextis.com, so pointing to official server

## Basic info

**Application name**:
**Application repo link**:
**Application home link**:
**Application description**:

## Qualifications

There are a ton of great Python projects out there, but what makes an
application "Awesome™"? Please check that all of the following criteria apply:

- [ ] Free software with an online source repository.
- [ ] Using Python for a considerable part of their functionality.
- [ ] Well-known, or at least prominently used in an identifiable niche.
- [ ] Maintained or otherwise demonstrably still functional on relevant platforms.
- [ ] An application, not a library or framework.

Note that installability via pip/PyPI and a developer-audience focus
may warrant a higher standard for inclusion, in keeping with the
spirit of the list:
http://sedimental.org/awesome_python_applications.html

### CODE REVIEW

**Comment by mahmoud** [comment]
Hey @doomedraven! Thanks for the update. Given that CAPEv1 is still receiving updates, the demo server is up, and it likely has an active install base, I'm thinking we add CAPEv2 as a separate entry, and remove CAPEv1 at a later date. Pointing to both projects may prove edifying for anyone looking at Py2 vs Py3. We should update the CAPEv1 description that it's deprecated, of course. Can you work with that?

**Comment by doomedraven** [comment]
Well isnt fully correct, in v1 there is note about end of life, the server
is up but isnt official and not mantained by the devs is why i point to the
official server

**Comment by mahmoud** [comment]
That's some good background information. The other repository having a fairly recent commit (Feb 11) made me think it was maintained I guess. I guess what I'm trying to say is that I'd like CAPEv2 to be added as a new applications, so it can get a new atom.xml entry, etc., because it's a new codebase. This list is fundamentally about reference, so the new codebase matters. If it's more convenient, you can just make the YAML changes, and I'll take care of the rest. :)

**Comment by doomedraven** [comment]
the update was done there by @kevoreilly, so maybe he has some clarificaiton why he maintaining dead project, well for me v1 is dead and nobody should use it as it has a lot of bugs which i fixed in v2, and i spend a lot of time doing v2 with a lot of bug fixes/improvements, so sorry if you not agree just close this, im not gonna update it to keep both

**Comment by mahmoud** [comment]
I think maybe I was unclear. I wanted CAPEv2 to be added as a new entry so that the atom.xml and `date_added` field would be correct, as this is technically a new project. I'm also interested in any context that would inform the removal of CAPEv1.

**Comment by doomedraven** [comment]
yes i got you, but nobody should use anymore v1, so i don't see reason to point users to that project with a lot of bugs and which dead, but kevin did some pushes there, well lets close this then and forget :)

**Pull request closed without merging**
