### PR TITLE
Add project: PathPicker

### PR DESCRIPTION
**Pull request by moshez**
## Basic info

**Application name**: PathPicker
**Application repo link**: https://github.com/facebook/PathPicker
**Application home link**: http://facebook.github.io/PathPicker/
**Application description**:  PathPicker presents you with a nice UI to select which files you're interested in. After that you can open them in your favorite editor or execute arbitrary commands. 

## Qualifications

- [x] Free software with an online source repository.
- [x] Using Python for a considerable part of their functionality.
- [x] Well-known, or at least prominently used in an identifiable niche.
- [x] Maintained or otherwise demonstrably still functional on relevant platforms.
- [x] An application, not a library or framework.

## Additional notability info

Standard tool used by Facebook engineers.

### CODE REVIEW

**Comment by mahmoud** [comment]
Looks good! I think this ought to go under the "dev" topic more than a "shell". "shell" is more for actual shells (a la bash, oil, xonsh, etc.)

**Comment by moshez** [comment]
It's not a *development* tool, though, it's a shell utility. If you do something like `find . -name "*.png" | fpp` and then choose to run the `gimp` command, so that you can choose which images to edit, it's an "artist" tool.

**Comment by mahmoud** [comment]
Hey I love the shell as much as anyone, but if all it's got is a CLI and it's primarily used by engineers, it's gonna have to go in `dev` until I get a better taxonomy ;)

**Comment by mahmoud** [comment]
Also shell is a subtopic under dev!

**Pull request merged**
